#include <joyctrl/configuration/action/key_down.hpp>
#include <joyctrl/log.hpp>

#include <map>

namespace joyctrl
{
namespace config
{
namespace action
{
KeyDown::KeyDown(const std::vector<std::string> &params) : Action(params)
{
    const std::map<std::string, VirtualKey> keys_map = {
        {"LButton", VirtualKey::LButton},
        {"RButton", VirtualKey::RButton},
        {"Cancel", VirtualKey::Cancel},
        {"Mbutton", VirtualKey::Mbutton},
        {"XButton1", VirtualKey::XButton1},
        {"XButton2", VirtualKey::XButton2},
        {"Back", VirtualKey::Back},
        {"Tab", VirtualKey::Tab},
        {"Clear", VirtualKey::Clear},
        {"Return", VirtualKey::Return},
        {"Shift", VirtualKey::Shift},
        {"Control", VirtualKey::Control},
        {"Menu", VirtualKey::Menu},
        {"Pause", VirtualKey::Pause},
        {"Capital", VirtualKey::Capital},
        {"Kana", VirtualKey::Kana},
        {"Hangeul", VirtualKey::Hangeul},
        {"Hangul", VirtualKey::Hangul},
        {"Ime_On", VirtualKey::Ime_On},
        {"Junja", VirtualKey::Junja},
        {"Final", VirtualKey::Final},
        {"Hanja", VirtualKey::Hanja},
        {"Kanji", VirtualKey::Kanji},
        {"Ime_Off", VirtualKey::Ime_Off},
        {"Escape", VirtualKey::Escape},
        {"Convert", VirtualKey::Convert},
        {"Nonconvert", VirtualKey::Nonconvert},
        {"Accept", VirtualKey::Accept},
        {"Modechange", VirtualKey::Modechange},
        {"Space", VirtualKey::Space},
        {"Prior", VirtualKey::Prior},
        {"Next", VirtualKey::Next},
        {"End", VirtualKey::End},
        {"Home", VirtualKey::Home},
        {"Left", VirtualKey::Left},
        {"Up", VirtualKey::Up},
        {"Right", VirtualKey::Right},
        {"Down", VirtualKey::Down},
        {"Select", VirtualKey::Select},
        {"Print", VirtualKey::Print},
        {"Execute", VirtualKey::Execute},
        {"Snapshot", VirtualKey::Snapshot},
        {"Insert", VirtualKey::Insert},
        {"Delete", VirtualKey::Delete},
        {"Help", VirtualKey::Help},
        {"Lwin", VirtualKey::Lwin},
        {"Rwin", VirtualKey::Rwin},
        {"Apps", VirtualKey::Apps},
        {"Sleep", VirtualKey::Sleep},
        {"Numpad0", VirtualKey::Numpad0},
        {"Numpad1", VirtualKey::Numpad1},
        {"Numpad2", VirtualKey::Numpad2},
        {"Numpad3", VirtualKey::Numpad3},
        {"Numpad4", VirtualKey::Numpad4},
        {"Numpad5", VirtualKey::Numpad5},
        {"Numpad6", VirtualKey::Numpad6},
        {"Numpad7", VirtualKey::Numpad7},
        {"Numpad8", VirtualKey::Numpad8},
        {"Numpad9", VirtualKey::Numpad9},
        {"Multiply", VirtualKey::Multiply},
        {"Add", VirtualKey::Add},
        {"Separator", VirtualKey::Separator},
        {"Subtract", VirtualKey::Subtract},
        {"Decimal", VirtualKey::Decimal},
        {"Divide", VirtualKey::Divide},
        {"F1", VirtualKey::F1},
        {"F2", VirtualKey::F2},
        {"F3", VirtualKey::F3},
        {"F4", VirtualKey::F4},
        {"F5", VirtualKey::F5},
        {"F6", VirtualKey::F6},
        {"F7", VirtualKey::F7},
        {"F8", VirtualKey::F8},
        {"F9", VirtualKey::F9},
        {"F10", VirtualKey::F10},
        {"F11", VirtualKey::F11},
        {"F12", VirtualKey::F12},
        {"F13", VirtualKey::F13},
        {"F14", VirtualKey::F14},
        {"F15", VirtualKey::F15},
        {"F16", VirtualKey::F16},
        {"F17", VirtualKey::F17},
        {"F18", VirtualKey::F18},
        {"F19", VirtualKey::F19},
        {"F20", VirtualKey::F20},
        {"F21", VirtualKey::F21},
        {"F22", VirtualKey::F22},
        {"F23", VirtualKey::F23},
        {"F24", VirtualKey::F24},
        {"NavigationView", VirtualKey::NavigationView},
        {"NavigationMenu", VirtualKey::NavigationMenu},
        {"NavigationUp", VirtualKey::NavigationUp},
        {"NavigationDown", VirtualKey::NavigationDown},
        {"NavigationLeft", VirtualKey::NavigationLeft},
        {"NavigationRight", VirtualKey::NavigationRight},
        {"NavigationAccept", VirtualKey::NavigationAccept},
        {"NavigationCancel", VirtualKey::NavigationCancel},
        {"Numlock", VirtualKey::Numlock},
        {"Scroll", VirtualKey::Scroll},
        {"OemNecEqual", VirtualKey::OemNecEqual},
        {"OemFjJisho", VirtualKey::OemFjJisho},
        {"OemFjMasshou", VirtualKey::OemFjMasshou},
        {"OemFjTouroku", VirtualKey::OemFjTouroku},
        {"OemFjLoya", VirtualKey::OemFjLoya},
        {"OemFjRoya", VirtualKey::OemFjRoya},
        {"LShift", VirtualKey::LShift},
        {"RShift", VirtualKey::RShift},
        {"LControl", VirtualKey::LControl},
        {"RControl", VirtualKey::RControl},
        {"LMenu", VirtualKey::LMenu},
        {"RMenu", VirtualKey::RMenu},
        {"BrowserBack", VirtualKey::BrowserBack},
        {"BrowserForward", VirtualKey::BrowserForward},
        {"BrowserRefresh", VirtualKey::BrowserRefresh},
        {"BrowserStop", VirtualKey::BrowserStop},
        {"BrowserSearch", VirtualKey::BrowserSearch},
        {"BrowserFavorites", VirtualKey::BrowserFavorites},
        {"BrowserHome", VirtualKey::BrowserHome},
        {"VolumeMute", VirtualKey::VolumeMute},
        {"VolumeDown", VirtualKey::VolumeDown},
        {"VolumeUp", VirtualKey::VolumeUp},
        {"MediaNextTrack", VirtualKey::MediaNextTrack},
        {"MediaPrevTrack", VirtualKey::MediaPrevTrack},
        {"MediaStop", VirtualKey::MediaStop},
        {"MediaPlayPause", VirtualKey::MediaPlayPause},
        {"LaunchMail", VirtualKey::LaunchMail},
        {"LaunchApp2", VirtualKey::LaunchApp2},
        {"Oem1", VirtualKey::Oem1},
        {"OemPlus", VirtualKey::OemPlus},
        {"OemComma", VirtualKey::OemComma},
        {"OemMinus", VirtualKey::OemMinus},
        {"OemPeriod", VirtualKey::OemPeriod},
        {"Oem2", VirtualKey::Oem2},
        {"Oem3", VirtualKey::Oem3},
        {"GamepadA", VirtualKey::GamepadA},
        {"GamepadB", VirtualKey::GamepadB},
        {"GamepadX", VirtualKey::GamepadX},
        {"GamepadY", VirtualKey::GamepadY},
        {"GamepadRightShoulder", VirtualKey::GamepadRightShoulder},
        {"GamepadLeftShoulder", VirtualKey::GamepadLeftShoulder},
        {"GamepadLeftTrigger", VirtualKey::GamepadLeftTrigger},
        {"GamepadRightTrigger", VirtualKey::GamepadRightTrigger},
        {"GamepadDpadUp", VirtualKey::GamepadDpadUp},
        {"GamepadDpadDown", VirtualKey::GamepadDpadDown},
        {"GamepadDpadLeft", VirtualKey::GamepadDpadLeft},
        {"GamepadDpadRight", VirtualKey::GamepadDpadRight},
        {"GamepadMenu", VirtualKey::GamepadMenu},
        {"GamepadView", VirtualKey::GamepadView},
        {"GamepadLeftThumbstickButton", VirtualKey::GamepadLeftThumbstickButton},
        {"GamepadRightThumbstickButton", VirtualKey::GamepadRightThumbstickButton},
        {"GamepadLeftThumbstickUp", VirtualKey::GamepadLeftThumbstickUp},
        {"GamepadLeftThumbstickDown", VirtualKey::GamepadLeftThumbstickDown},
        {"GamepadLeftThumbstickRight", VirtualKey::GamepadLeftThumbstickRight},
        {"GamepadLeftThumbstickLeft", VirtualKey::GamepadLeftThumbstickLeft},
        {"GamepadRightThumbstickUp", VirtualKey::GamepadRightThumbstickUp},
        {"GamepadRightThumbstickDown", VirtualKey::GamepadRightThumbstickDown},
        {"GamepadRightThumbstickRight", VirtualKey::GamepadRightThumbstickRight},
        {"GamepadRightThumbstickLeft", VirtualKey::GamepadRightThumbstickLeft},
        {"Oem4", VirtualKey::Oem4},
        {"Oem5", VirtualKey::Oem5},
        {"Oem6", VirtualKey::Oem6},
        {"Oem7", VirtualKey::Oem7},
        {"Oem8", VirtualKey::Oem8},
        {"OemAx", VirtualKey::OemAx},
        {"Oem102", VirtualKey::Oem102},
        {"IcoHelp", VirtualKey::IcoHelp},
        {"Ico00", VirtualKey::Ico00},
        {"ProcessKey", VirtualKey::ProcessKey},
        {"IcoClear", VirtualKey::IcoClear},
        {"Packet", VirtualKey::Packet},
        {"OemReset", VirtualKey::OemReset},
        {"OemJump", VirtualKey::OemJump},
        {"OemPa1", VirtualKey::OemPa1},
        {"OemPa2", VirtualKey::OemPa2},
        {"OemPa3", VirtualKey::OemPa3},
        {"OemWsctrl", VirtualKey::OemWsctrl},
        {"OemCusel", VirtualKey::OemCusel},
        {"OemAttn", VirtualKey::OemAttn},
        {"OemFinish", VirtualKey::OemFinish},
        {"OemCopy", VirtualKey::OemCopy},
        {"OemAuto", VirtualKey::OemAuto},
        {"OemEnlw", VirtualKey::OemEnlw},
        {"OemBacktab", VirtualKey::OemBacktab},
        {"Attn", VirtualKey::Attn},
        {"Crsel", VirtualKey::Crsel},
        {"Exsel", VirtualKey::Exsel},
        {"Ereof", VirtualKey::Ereof},
        {"Play", VirtualKey::Play},
        {"Zoom", VirtualKey::Zoom},
        {"Noname", VirtualKey::Noname},
        {"Pa1", VirtualKey::Pa1},
        {"OemClear", VirtualKey::OemClear},
    };

    if (keys_map.count(mParams[0]) != 0)
    {
        mKey = keys_map.at(mParams[0]);
    }
}

void KeyDown::start(ForegroundWindow &fg_window)
{
    fg_window.simulateKeyDown(mKey);
}
} // namespace action
} // namespace config
} // namespace joyctrl
